server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411    #表示监控的数据去哪里看
    sleuth:
      sampler:
        #采样率介于0到1之间，1表示全部采集
      probability: 1

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/dbcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cn.cloud.entity
eureka:
  client:
    #表示是否将自己注册eurekaserver默认为true
    register-with-eureka: true
    #是否从eurekaserver抓取已有的注册信息，默认true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001  #修改主机名
    prefer-ip-address: true  #访问路径可以显示ip地址
    #lease-renewal-interval-in-seconds: 1 #eureka客户端服务发送心跳的时间间隔，单位为秒（默认是30s）
    #lease-expiration-duration-in-seconds: 2 #eureka服务端收到最后一次心跳后等待时间上限，单位为秒（默认是90s）超时将剔除服务
