server:
  port: 3344
spring:
  application:
    name: cloud-config #注册进eureka服务器的微服务名称
  cloud:
    config:
      server:
        git:
          uri: https://github.com/usernameyangxiaoliang/springcloud-config.git #git@github.com:usernameyangxiaoliang/springcloud-config.git #github上仓库名称
          search-paths: #搜索目录
            - springcloud-config
      label: master #读取的分支
  #rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    #表示是否将自己注册eurekaserver默认为true
    register-with-eureka: true
    #是否从eurekaserver抓取已有的注册信息，默认true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    #fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#使用cmd命令行对config进行刷新 curl -X POST "http://localhost:3344/actuator/bus-refresh"
#一次刷新处处生效
#如果想制定配置生效呢？curl -X POST "http://localhost:3344/actuator/bus-refresh/config-client:3355"
#格式为curl -X POST "http://localhost:3344/actuator/bus-refresh/微服务名称:端口"
#暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
